export const en = {
    home: "Home",
    profile: "Profile",
    password: "Password",
    username: "Username",
    login: "Log In",
    logout: "Log Out",
    login_failed: "Login Failed",
    search: "Search ...",
    menu: "Menu",
    close: "Close",
    unfollow: "Unfollow",
    follow: "Follow",
    requested: "Requested",
    data_policy: "Data Policy",
    likes: "Likes",
    comments: "Comments",
    comment: "Comment",
    like: "Like",
    edit: "Edit",
    delete: "Delete",
    share: "Share",
    report: "Report",
    blockuser: "Block User",
    page_not_found: "Page Not Found",
    imprint: "Imprint",
    terms_of_use: "Terms of Use",
    following: "Following",
    followers: "Followers",
    follower: "Follower",
    posts: "Posts",
    post: "Post",
    deleteaccount: "Delete Account",
    darkmode: "Dark Mode",
    lightmode: "Light Mode",
    modernblue: "Modern Blue",
    snow: "Snow",
    discover: "Discover",
    chat: "Chat",
    join: "Join",
    leave: "Leave",
    member: "Member",
    members: "Members",
    description: "Description",
    group: "Group",
    groups: "Groups",
    yourgroup: "Your Group",
    vote: "Vote",
    votes: "Votes",
    thousand_abbreviation: "K",
    million_abbreviation: "M",
    billion_abbreviation: "B",
    similarposts: "Similar Posts",
    testflightmessage: "Download the iOS beta and help us test it 🥳",
    accountdeleted: "Your account has been deleted",
    error: "Error",
    nodatagroups: "Groups that you own or have joined are shown here",
    nodata: "No Data",
    nopostsyet: "No posts yet",
    secondsago: ". seconds ago",
    minutesago: ". minutes ago",
    hoursago: ". hours ago",
    daysago: ". days ago",
    weeksago: ". weeks ago",
    monthsago: ". months ago",
    yearsago: ". years ago",
    secondago: ". second ago",
    minuteago: ". minute ago",
    hourago: ". hour ago",
    dayago: ". day ago",
    weekago: ". week ago",
    monthago: ". month ago",
    yearago: ". year ago",
    nocommentsyet: "No comments yet",
    loadxmorereplies: "Load . more replies",
    loadmore: "Load more",
    loadonemorereply: "Load one more reply",
    indexwelcome: "Connect with friends, join groups, or learn more about the world.",
    successfullyreported: "Successfully reported",
    download: "Download",
    meta_keywords: "Social network, make friends, find partners, dating, connect, knoggl, ios, android, social, media",
    meta_description: "Knoggl is a social network that takes special care to protect your privacy.",
    follow_to_see_posts: "Follow . to see the posts",

    index_discover_title: "Discover knoggl.",
    index_no_compromises_title: "No compromise!",
    index_discover_content: "Knoggl is a social network that attaches particular importance to protecting your privacy. Knoggl mainly uses chronological feeds so you won't be suggested content that doesn't interest you.",
    index_no_compromises_content: "Even if we protect your data, you don't have to forego functionality. On Knoggl you can share posts, find friends, create or join groups, chat with people and much more.",

    index_profile_title: "Design your profile as you want it.",
    index_profile_content_p1: "Knoggl offers you many options to customize your profile the way you like it! Change your profile and cover photo, write whatever you want in your bio and create posts that bring your profile to life.",
    index_profile_content_p2: "If everything gets on your nerves at some point, you can simply set your profile to private and enjoy the peace and quiet.",
    
    index_no_data_selling_title: "Did you know that we don't sell your data?",
    index_no_data_selling_content: "Most other social networks trade your private information to maximize profits. Knoggl does not do this! Your data will never be passed on to third parties, neither for money nor for chocolate.",

    index_chat_title: "Chat with your friends.",
    index_chat_content_p1: "Chat with your friends or acquaintances. Send videos, pictures, voice messages or just text. Share your favorite groups, posts or profiles.",
    index_chat_content_p2: "There are hardly any limits to Knoggl Chat. All your messages are stored centrally so you can access them from anywhere, on any device.",

    profile_picture_of: "Profile picture of .",
    cover_photo_by: "Cover photo by .",

    index_group_title: "Knoggl groups are great!",
    index_group_content_p1: "Knoggl groups are similar to profiles, with the big difference that every member can create posts!",
    index_group_content_p2: "Search for groups you might like or simply create one yourself!",

    index_add_post_title: "Post what you want.",
    index_add_post_content_p1: "Create posts exactly how you like them. You can create image, video, poll or just text posts. The text can contain as many links, #hashtags and @mentions as fit within the 1,500 character limit!",
    index_add_post_content_p2: "If you made a mistake, you can correct the text of your post as many times as you like. If you want your post to get more attention, make sure you use #hashtags that match the post.",
};
