export const es = {
    home: "Casa",
    profile: "Perfil",
    password: "Clave",
    username: "Nombre de usuario",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    login_failed: "Error de inicio de sesion",
    search: "Búsqueda ...",
    menu: "Menú",
    close: "Cerrar",
    unfollow: "Dejar de seguir",
    follow: "Seguir",
    requested: "Solicitado",
    data_policy: "Política de datos",
    likes: "Gustos",
    comments: "Comentarios",
    comment: "Comentario",
    like: "Me gusta",
    edit: "Editar",
    delete: "Borrar",
    share: "Cuota",
    report: "Reporte",
    blockuser: "Bloquear usuario",
    page_not_found: "Página no encontrada",
    imprint: "Imprimir",
    terms_of_use: "Términos de Uso",
    following: "Siguiente",
    followers: "Seguidores",
    follower: "Seguidor",
    posts: "Publicaciones",
    post: "Correo",
    deleteaccount: "Borrar cuenta",
    darkmode: "Modo oscuro",
    lightmode: "Modo de luz",
    modernblue: "Azul moderno",
    snow: "Nieve",
    discover: "Descubrir",
    chat: "Chat",
    join: "Entrar",
    leave: "Abandonar",
    member: "Miembro",
    members: "Miembros",
    description: "Descripción",
    group: "Grupo",
    groups: "Grupos",
    yourgroup: "Tu grupo",
    vote: "Votar",
    votes: "Votos",
    thousand_abbreviation: "K",
    million_abbreviation: "MM",
    billion_abbreviation: "M",
    similarposts: "Publicaciones similares",
    testflightmessage: "Descarga la beta de iOS y ayúdanos a probarlo",
    accountdeleted: "Tu cuenta ha sido eliminada",
    error: "Error",
    nodatagroups: "Los grupos de los que eres propietario o a los que te has unido se muestran aquí",
    nodata: "Sin datos",
    nopostsyet: "Aún no hay publicaciones",
    secondsago: "hace . segundos",
    minutesago: "hace . minutos",
    hoursago: "hace . horas",
    daysago: "hace . días",
    weeksago: "hace . semanas",
    monthsago: "hace . meses",
    yearsago: "hace . años",
    secondago: "hace . segundos",
    minuteago: "hace . minuto",
    hourago: "hace . hora",
    dayago: "hace . día",
    weekago: "hace . semana",
    monthago: "hace . meses",
    yearago: "hace . año",
    nocommentsyet: "Sin comentarios aún",
    loadxmorereplies: "Cargar . respuestas más",
    loadmore: "Carga más",
    loadonemorereply: "Cargar una respuesta más",
    indexwelcome: "Conéctate con amigos, únete a grupos o aprende más sobre el mundo.",
    successfullyreported: "Reportado con éxito",
    download: "Descargar",
    meta_keywords: "Red social, hacer amigos, encontrar socios, citas, conectarse, knoggl, ios, android, social, medios",
    meta_description: "Knoggl es una red social que tiene especial cuidado en proteger tu privacidad.",
    follow_to_see_posts: "Sigue a . para ver las publicaciones",

    index_discover_title: "Descubre knogl.",
    index_no_compromises_title: "¡Sin compromiso!",
    index_discover_content: "Knoggl es una red social que otorga especial importancia a la protección de su privacidad. Knoggl utiliza principalmente „feeds” cronológicos para que no se le sugiera contenido que no le interese.",
    index_no_compromises_content: "Incluso si protegemos sus datos, no tiene que renunciar a la funcionalidad. En Knoggl puede compartir publicaciones, encontrar amigos, crear o unirse a grupos, chatear con personas y mucho más.",

    index_profile_title: "Diseña tu perfil como tú quieras.",
    index_profile_content_p1: "¡Knoggl te ofrece muchas opciones para personalizar tu perfil como más te guste! Cambia tu perfil y foto de portada, escribe lo que quieras en tu biografía y crea publicaciones que den vida a tu perfil.",
    index_profile_content_p2: "Si todo lo pone nervioso en algún momento, simplemente puede configurar su perfil como privado y disfrutar de la paz y la tranquilidad.",

    index_no_data_selling_title: "¿Sabías que no vendemos tus datos?",
    index_no_data_selling_content: "La mayoría de las otras redes sociales intercambian su información privada para maximizar las ganancias. ¡Knoggl no hace esto! Tus datos nunca serán cedidos a terceros, ni por dinero ni por chocolate.",

    index_chat_title: "Chatea con tus amigos.",
    index_chat_content_p1: "Chatea con tus amigos o conocidos. Envía videos, fotos, audios o simplemente texto. Comparte tus grupos, publicaciones o perfiles favoritos.",
    index_chat_content_p2: "Casi no hay límites para Knoggl Chat. Todos sus mensajes se almacenan de forma centralizada para que pueda acceder a ellos desde cualquier lugar, en cualquier dispositivo.",

    profile_picture_of: "Foto de perfil de .",
    cover_photo_by: "Foto de portada por .",
};
